//
//  ReportPDF.swift
//  Polar Pill
//
//  PDF export of the adherence report ("Share with clinician" / "Download PDF").
//  Renders a printable SwiftUI layout to a single-page PDF via ImageRenderer.
//

import SwiftUI
import UIKit

/// Snapshot of everything the PDF needs (decoupled from the view model).
struct ReportData {
    let memberName: String
    let periodTitle: String   // "Weekly Report"
    let periodLabel: String   // "16–22 July"
    let dosesTaken: Int
    let dosesScheduled: Int
    let adherencePercent: Int
    let days: [AdherenceDay]
    let summaryText: String?
}

enum ReportPDF {
    /// Renders the report to a temporary PDF file and returns its URL.
    @MainActor
    static func render(data: ReportData) -> URL? {
        let content = ReportPDFView(data: data)
            .frame(width: 612) // US Letter width in points
        let renderer = ImageRenderer(content: content)

        let filename = "Polar Pill Report — \(data.memberName), \(data.periodLabel).pdf"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)

        renderer.render { size, renderInContext in
            var mediaBox = CGRect(origin: .zero, size: size)
            guard let consumer = CGDataConsumer(url: url as CFURL),
                  let context = CGContext(consumer: consumer, mediaBox: &mediaBox, nil) else {
                return
            }
            context.beginPDFPage(nil)
            renderInContext(context)
            context.endPDFPage()
            context.closePDF()
        }

        return FileManager.default.fileExists(atPath: url.path) ? url : nil
    }
}

/// Printable layout — deliberately plain, white background, no interactivity.
private struct ReportPDFView: View {
    let data: ReportData

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            // Header
            HStack {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Polar Pill — \(data.periodTitle)")
                        .font(.title.bold())
                    Text("\(data.memberName) · \(data.periodLabel)")
                        .font(.headline)
                        .foregroundStyle(.secondary)
                }
                Spacer()
                Image("Mascot")
                    .resizable()
                    .scaledToFit()
                    .frame(width: 52, height: 52)
            }

            Divider()

            // Stats
            HStack(spacing: 36) {
                VStack(alignment: .leading, spacing: 2) {
                    Text("\(data.dosesTaken)/\(data.dosesScheduled)")
                        .font(.largeTitle.bold())
                    Text("doses taken")
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                }
                VStack(alignment: .leading, spacing: 2) {
                    Text("\(data.adherencePercent)%")
                        .font(.largeTitle.bold())
                        .foregroundStyle(Theme.primary)
                    Text("adherence")
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                }
                Spacer()
            }

            // Chart
            if !data.days.isEmpty {
                WeeklyBarChart(days: data.days)
                    .padding(.vertical, 8)
            }

            // Summary
            if let summaryText = data.summaryText {
                VStack(alignment: .leading, spacing: 6) {
                    Text("SUMMARY")
                        .font(.footnote.bold())
                        .foregroundStyle(Theme.primary)
                    Text(summaryText)
                        .font(.body)
                }
            }

            Divider()

            Text("Generated by Polar Pill on \(Date.now.formatted(date: .long, time: .shortened)). For informational purposes only — not medical advice.")
                .font(.caption2)
                .foregroundStyle(.secondary)
        }
        .padding(36)
        .background(.white)
        .environment(\.colorScheme, .light)
    }
}

// MARK: - Share sheet

/// A URL payload for `.sheet(item:)` presentation.
struct SharePayload: Identifiable {
    let id = UUID()
    let url: URL
}

/// UIActivityViewController wrapper (share sheet).
struct ShareSheet: UIViewControllerRepresentable {
    let items: [Any]

    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }

    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}
